# Nome da nossa aplicação
spring.application.name=financas-casal-api

# Configurações do Banco de Dados H2 (Em memória)
spring.datasource.url=jdbc:h2:mem:financasdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Habilitar o painel visual do H2 no navegador
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Configurações do JPA/Hibernate (A mágica que cria as tabelas)
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true